/**
 * Internal implementation detail.
 *
 * Internal implementation detail.
 * Internal implementation detail.
 * Internal implementation detail.
 *        SMTP_HOST=smtp.tu-proveedor.com
 *        SMTP_PORT=587
 * Internal implementation detail.
 * Internal implementation detail.
 * Internal implementation detail.
 *   2. Change ALERTS_ENABLED to `true` in this file.
 *
 * Proveedores compatibles:
 *   - Gmail:      SMTP_HOST=smtp.gmail.com, SMTP_PORT=587 (requiere App Password 2FA)
 *   - Outlook365: SMTP_HOST=smtp.office365.com, SMTP_PORT=587
 *   - SendGrid:   SMTP_HOST=smtp.sendgrid.net, SMTP_PORT=587, SMTP_USER=apikey
 *
 * Internal implementation detail.
 * Internal implementation detail.
 * Internal implementation detail.
 */

// ─── INTERRUPTOR PRINCIPAL ──────────────────────────────────────────────────
// Internal implementation detail.
const ALERTS_ENABLED = false;
// ────────────────────────────────────────────────────────────────────────────

import nodemailer from 'nodemailer';

/* Internal implementation detail. */
const ADMIN_ALERT_EMAIL = 'ismaelcorra@gmail.com';

/* Internal implementation detail. */
const ALERT_COOLDOWN_MS = 15 * 60 * 1000;

/* Internal implementation detail. */
const lastAlertByIdentity = new Map<string, number>();

/* Internal implementation detail. */
interface LoginLockoutAlertInput {
  email: string;       // Email intentado
  ip: string;          // Source IP address for the attempts.
  blockedSeconds: number; // Duration of the block in seconds.
}

/* Internal implementation detail. */
function buildIdentityKey(input: LoginLockoutAlertInput): string {
  return `${(input.email || '').trim().toLowerCase()}|${(input.ip || '').trim().toLowerCase()}`;
}

/* Internal implementation detail. */
function shouldSendAlert(identityKey: string): boolean {
  const now = Date.now();
  const last = lastAlertByIdentity.get(identityKey) || 0;
  if (now - last < ALERT_COOLDOWN_MS) {
    return false; // demasiado pronto, omitir
  }
  lastAlertByIdentity.set(identityKey, now); // Record the current timestamp.
  return true;
}

/**
 * Internal implementation detail.
 * Internal implementation detail.
 */
function getMailerConfig() {
  const host = process.env.SMTP_HOST || '';
  const port = Number.parseInt(process.env.SMTP_PORT || '587', 10);
  const user = process.env.SMTP_USER || '';
  const pass = process.env.SMTP_PASS || '';
  const from = process.env.SMTP_FROM || user || '';

  if (!host || !port || !user || !pass || !from) {
    return null; // Do not send when SMTP configuration is incomplete.
  }

  return {
    host,
    port,
    secure: port === 465, // Port 465 uses direct SSL; other ports use STARTTLS.
    auth: { user, pass },
    from,
  };
}

/**
 * Internal implementation detail.
 * Internal implementation detail.
 *
 * Internal implementation detail.
 *
 * Internal implementation detail.
 * Internal implementation detail.
 */
export async function sendLoginLockoutAlert(input: LoginLockoutAlertInput): Promise<boolean> {
  // Internal implementation detail.
  if (!ALERTS_ENABLED) {
    console.warn('[security-alert] Alerts are disabled (ALERTS_ENABLED=false). To enable them, edit securityAlerts.ts', {
      email: input.email,
      ip: input.ip,
      blockedSeconds: input.blockedSeconds,
    });
    return false;
  }

  const identityKey = buildIdentityKey(input);
  if (!shouldSendAlert(identityKey)) {
    return false; // Do not send again during the cooldown period.
  }

  const config = getMailerConfig();
  if (!config) {
    // Internal implementation detail.
    console.warn('[security-alert] SMTP is not configured; alert not sent', {
      email: input.email,
      ip: input.ip,
      blockedSeconds: input.blockedSeconds,
      adminEmail: ADMIN_ALERT_EMAIL,
    });
    return false;
  }

  // Internal implementation detail.
  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: config.auth,
  });

  const now = new Date().toISOString();

  // Internal implementation detail.
  await transporter.sendMail({
    from: config.from,
    to: ADMIN_ALERT_EMAIL,
    subject: '[HVAC App] Security Alert: Too many login attempts',
    text: [
      'Security alert generated by HVAC App.',
      `Time: ${now}`,
      `Email attempted: ${input.email || '(empty)'}`,
      `IP: ${input.ip || '(unknown)'}`,
      `Blocked for: ${input.blockedSeconds}s`,
    ].join('\n'),
  });

  return true;
}
